[project]
name = "BD2ModManager"
version = "2.3.0"
requires-python = ">=3.13"
dependencies = [
    "pefile>=2024.8.26",
    "pyside6>=6.9.0",
    "requests>=2.32.3",
]

[dependency-groups]
dev = [
    "ruff>=0.11.12",
]
